name:                 syt
version:              0.1.0.0
visibility:           public
id:                   syt-0.1.0.0-inplace
key:                  syt-0.1.0.0-inplace
license:              BSD-3-Clause
maintainer:           198982749+Copilot@users.noreply.github.com
author:               copilot-swe-agent[bot]
abi:                  inplace
exposed:              True
exposed-modules:      MyLib
import-dirs:
    /home/runner/work/syt/syt/dist-newstyle/build/x86_64-linux/ghc-9.12.2/syt-0.1.0.0/build

library-dirs:
    /home/runner/work/syt/syt/dist-newstyle/build/x86_64-linux/ghc-9.12.2/syt-0.1.0.0/build

library-dirs-static:
    /home/runner/work/syt/syt/dist-newstyle/build/x86_64-linux/ghc-9.12.2/syt-0.1.0.0/build

dynamic-library-dirs:
    /home/runner/work/syt/syt/dist-newstyle/build/x86_64-linux/ghc-9.12.2/syt-0.1.0.0/build

data-dir:             /home/runner/work/syt/syt/.
hs-libraries:         HSsyt-0.1.0.0-inplace
depends:              base-4.21.0.0-ae91
haddock-interfaces:
    /home/runner/work/syt/syt/dist-newstyle/build/x86_64-linux/ghc-9.12.2/syt-0.1.0.0/doc/html/syt/syt.haddock

haddock-html:
    /home/runner/work/syt/syt/dist-newstyle/build/x86_64-linux/ghc-9.12.2/syt-0.1.0.0/doc/html/syt
